/** Response from GET /status */
export interface NodeStatus {
  version: string;
  network: string;
  block_height: number;
  peer_count: number;
  synced: boolean;
  timestamp: string;
}

/** Response from GET /accounts/:address */
export interface AccountInfo {
  address: string;
  balance: number;
  nonce: number;
  tx_count: number;
}

/** Response from GET /transactions/:hash */
export interface TransactionInfo {
  hash: string;
  sender: string;
  recipient: string;
  amount: number;
  fee: number;
  block_height: number | null;
  status: string;
  timestamp: number;
}

/** JSON-RPC 2.0 response envelope */
export interface JsonRpcResponse<T = unknown> {
  jsonrpc: string;
  result?: T;
  error?: {
    code: number;
    message: string;
    data?: unknown;
  };
  id: number | string;
}

/** WebSocket event: new block finalized */
export interface NewBlockEvent {
  type: "new_block";
  height: number;
  hash: string;
  tx_count: number;
  timestamp: number;
}

/** WebSocket event: new transaction in mempool */
export interface NewTransactionEvent {
  type: "new_transaction";
  hash: string;
  sender: string;
  recipient: string;
  amount: number;
}

export type NodeEvent = NewBlockEvent | NewTransactionEvent;

/** Payment request generated by the merchant terminal */
export interface PaymentRequest {
  id: string;
  address: string;
  amount: number;
  createdAt: number;
  status: "pending" | "confirmed" | "expired";
  txHash?: string;
  sender?: string;
}

/** Merchant transaction record for local history */
export interface MerchantTransaction {
  id: string;
  hash: string;
  amount: number;
  sender: string;
  status: "pending" | "confirmed";
  timestamp: number;
  memo?: string;
}
